services:
  - type: web
    name: telemetria-bruno-listener
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: MQTT_USERNAME
        sync: false
      - key: MQTT_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: MQTT_CLIENT_ID
        value: telemetria-listener-render
      - key: STREAM_NOTIFY_URL
        sync: false
      - key: STREAM_NOTIFY_SECRET
        sync: false
